# code: language=ansible
---
- name: Remove nginx vhost file
  ansible.builtin.file:
    path: "{{ nginx_conf_base_dir }}/{{ nginx_vhost_dir }}/{{ nginx_vhost_filename }}.conf"
    state: absent
  notify:
    - Restart nginx

- name: Remove certificates
  ansible.builtin.file:
    path: "/etc/letsencrypt/live/{{ keycloak_server_name }}"
    state: absent

- name: Close http and https ports using firewalld
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: disabled
    offline: true
  loop:
    - "{{ nginx_vhost_http_listen_port }}/tcp"
    - "{{ nginx_vhost_https_listen_port }}/tcp"
  when: firewalld_installed
  notify:
    - Restart firewalld if running
