# code: language=ansible
---
- name: Remove keycloak database
  become_user: postgres
  become: true
  community.postgresql.postgresql_db:
    name: "{{ postgres_keycloak_db }}"
    state: absent

- name: Remove keycloak database user
  become_user: postgres
  become: true
  community.postgresql.postgresql_user:
    name: "{{ postgres_keycloak_user }}"
    state: absent
