# code: language=ansible
---
- name: Install postgresql
  when: postgres_install == 'true'
  community.general.zypper:
    name:
      - postgresql15
      - postgresql15-server
      - postgresql15-contrib
      - postgresql15-server-devel
    state: present
    update_cache: true

- name: Install postgres python management deps
  ansible.builtin.pip:
    name:
      - psycopg2-binary
    state: present

- name: Start postgresql service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: "Configure postgres to listen on *"
  become_user: postgres
  become: true
  community.postgresql.postgresql_set:
    name: listen_addresses
    value: "*"
  notify: Restart postgres

# this task is implemented with `lineinfile` instead of `pg_hba` module
# as the second want does not provide any option to set the order of
# the new entry, and this case, the new entry must be pretty much on top
# of the host entries to apply properly the precedence of rules
- name: Configure pg_hba to accept connection from keycloak
  become_user: postgres
  become: true
  notify: Restart postgres
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: "^host.*{{ postgres_keycloak_db }}"
    insertafter: "^local.*all.*all.*peer"
    line: "host\t{{ postgres_keycloak_db }}\t{{ postgres_keycloak_user }}\t0.0.0.0/0\tmd5"

- name: Create postgres keycloak database
  become_user: postgres
  become: true
  community.postgresql.postgresql_db:
    name: "{{ postgres_keycloak_db }}"
    state: present

- name: Create keycloak database user
  become_user: postgres
  become: true
  community.postgresql.postgresql_user:
    db: "{{ postgres_keycloak_db }}"
    name: "{{ postgres_keycloak_user }}"
    password: "{{ keycloak_postgres_password }}"
    comment: "Keycloak user provisioned by playbook"
    state: present

- name: Grant privilegies to the keycloak user for the keycloak database
  become_user: postgres
  become: true
  community.postgresql.postgresql_privs:
    db: "{{ postgres_keycloak_db }}"
    objs: public
    roles: "{{ postgres_keycloak_user }}"
    privs: ALL
    type: schema
    state: present
